### PR TITLE
fix(named type): Warn about reserved characters, fixes #335

### LINKED ISSUE #335: MSON Named Types - parsed as variable
Following MSON Named type
```md
## *User (object)*
- m1
```

is parsed as variable:
```js
...
    "element": "dataStructure",
          "name": {
            "literal": "User (object)",
            "variable": true
          },
...
```

according to discussion with @zdne it is bug

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

File: src/MSONNamedTypeParser.h [hunk 1]
```diff
@@ -15,6 +15,9 @@ using namespace scpl;
 
 namespace snowcrash {
 
+    /** MSON reserved characters matching regex */
+    const char* const MSONReservedCharsRegex = "[]:\()<>\{}[_*+`-]?";
```
Comment (kylef) [inline src/MSONNamedTypeParser.h]: Should backtick really be in here? Since it's used to escape reserved characters. Wouldn't using a backtick would result in the following warning?

```
please escape the name of the data structure using backticks since it contains MSON reserved characters
```

Comment (pksunkara) [inline src/MSONNamedTypeParser.h]: Hmm.. yeah.

**Comment by w-vi** [comment]
And include test using the backticks as escaping so we are sure not to break escaping in the future

File: src/MSONNamedTypeParser.h (hunk 1 above)
Comment (pksunkara) [inline src/MSONNamedTypeParser.h]: Actually, the backticks will be stripped, so we won't be having any issues here. I thought there might be issues with nested escaped characters, but that case will also not be a problem here. So, the regex is correct.

**Comment by pksunkara** [comment]
@kylef This is now updated. Please R&M
